# Generated by Django 5.0.4 on 2024-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('userRating', models.CharField(max_length=10)),
            ],
        ),
    ]
