# Generated by Django 5.0.4 on 2024-04-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_description_alter_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPAARating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(to='core.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaaRating',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mpaarating'),
            preserve_default=False,
        ),
    ]
