# Generated by Django 5.0.4 on 2024-04-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mpaaRating',
        ),
    ]
