# Generated by Django 5.0.4 on 2024-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_mpaarating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='core.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaaRating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mpaarating'),
        ),
    ]
