# Generated by Django 5.0.4 on 2024-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_genre_movies_movie_genres_movie_mpaarating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mpaaRating',
        ),
    ]
