# Generated by Django 5.0.4 on 2024-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_movie_genres_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(max_length=1000),
        ),
    ]
