# Generated by Django 5.0.4 on 2024-04-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_genre', to='core.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_genre', to='core.genre'),
        ),
    ]
